# Generated by Django 4.2.7 on 2023-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='studentimages')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('NB', 'NON BINARY')], max_length=200)),
                ('Matric_number', models.IntegerField()),
                ('faculty', models.CharField(choices=[('SC', 'FACULTY OF SCIENCE'), ('SMS', 'FACULTY OF SOCIAL AND MANAGEMENT SCIENCES'), ('ART', 'FACULTY OF ART')], max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
